---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.multicron.puppypod.io
  resources:
  - cronjobsamples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.multicron.puppypod.io
  resources:
  - cronjobsamples/finalizers
  verbs:
  - update
- apiGroups:
  - batch.multicron.puppypod.io
  resources:
  - cronjobsamples/status
  verbs:
  - get
  - patch
  - update
